### ISSUE TITLE
Duplicate boundwithParts generated

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/MARC21-To-FOLIO#114] opened 2022-01-19 12:46 UTC
Posting results in this error:
`Row 39118       HTTP 422         lower(f_unaccent(jsonb ->> 'itemId'::text)), lower(f_unaccent(jsonb ->> 'holdingsRecordId'::text)) value already exists in table bound_with_part: c62ee958-03a9-54bd-8480-842d897a393f, 3e4bfac5-735d-5704-904e-15127544b9a9`

The data posted:
```
boundwithPart   {"id": "34931612-e4b2-48bf-9b21-df23e213ce2d", "holdingsRecordId": "3e4bfac5-735d-5704-904e-15127544b9a9", "itemId": "c62ee958-03a9-54bd-8480-842d897a393f"}
boundwithPart   {"id": "c88f441b-955e-4c18-8ea7-67e875ecfffc", "holdingsRecordId": "3e4bfac5-735d-5704-904e-15127544b9a9", "itemId": "c62ee958-03a9-54bd-8480-842d897a393f"}
```

The legacy ID of the duplicated holding and item:

```
{"legacy_id": "i10019777", "folio_id": "3e4bfac5-735d-5704-904e-15127544b9a9"}
{"legacy_id": "b10019741", "folio_id": "3e4bfac5-735d-5704-904e-15127544b9a9"}
{"legacy_id": "b10332984", "folio_id": "3e4bfac5-735d-5704-904e-15127544b9a9"}

```
The source data:
`['b10019741', 'b10332984']      i10019777       973 S73l v. 2   ['973 S73L', '']        31826000019779  0       clst    v.2     1       -       -                               0               False   ['973 S73L', '']`

Note that the two legacy boundwith bibs appear to have been mapped to the same FOLIO holding, instead of separate ones.
Shouldn't the ID map output be something more along the lines of
```
{"legacy_id": "i10019777", "folio_id": "holding1"}
{"legacy_id": "b10019741", "folio_id": "holding1"}
{"legacy_id": "b10332984", "folio_id": "holding2"}
```

**Comment by fontanka16** [comment] 2022-01-19 14:27
A theory for the first error  is that the .extradata was not cleaned out between runs.

**Comment by fontanka16** [comment] 2022-01-31 20:41
@branchedelac closing this since I have not been able to reproduce this since my last update.

**Closed by fontanka16** 2022-01-31 20:41 UTC
Labels: bug
